/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.mag.telas;

import br.com.mag.classe.Situacao;
import br.com.mag.dao.SituacaoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Tela_Situacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_situacao
     */
    public Tela_Situacao() {
        initComponents();
    }
    
    
    public void listarStiuacao(){
         try {
            SituacaoDAO dao = new SituacaoDAO();
            List<Situacao> lista = dao.listsituacao();
            
                DefaultTableModel modelo = (DefaultTableModel)tbSituacao.getModel();
                modelo.setNumRows(0);
                
                for(Situacao s: lista){
                   modelo.addRow(new Object[]{
                       s.getIdsit(), 
                       s.getSituacao()
                   });
                    
                }
            
        } catch (Exception e) {
        }
    }
    
    public void limpaCampos(){
        txtIdSit.setText(null);
        txtSit.setText(null);
        
        btnDel.setEnabled(false);
        btnUp.setEnabled(false);
        btnAdd.setEnabled(true);
    }
    
     public void setar_campo(){
        int setar = tbSituacao.getSelectedRow();
        txtIdSit.setText(tbSituacao.getModel().getValueAt(setar, 0).toString());
        txtSit.setText(tbSituacao.getModel().getValueAt(setar, 1).toString());
        btnAdd.setEnabled(false);
        btnUp.setEnabled(true);
        btnDel.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdSit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSituacao = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSit = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPesId = new javax.swing.JTextField();
        txtPesSit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Situação");
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(709, 541));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Código");

        txtIdSit.setEnabled(false);
        txtIdSit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSitActionPerformed(evt);
            }
        });

        tbSituacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Situação"
            }
        ));
        tbSituacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSituacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSituacao);

        jLabel2.setText("Situação");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mag/icone/addOs.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mag/icone/upOs.png"))); // NOI18N
        btnUp.setEnabled(false);
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mag/icone/delOs.png"))); // NOI18N
        btnDel.setEnabled(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        jLabel3.setText("Código");

        txtPesId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesIdKeyReleased(evt);
            }
        });

        jLabel4.setText("Situação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(57, 57, 57)
                                .addComponent(btnUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(btnDel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdSit)
                                    .addComponent(txtSit, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(txtPesId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesSit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesSit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdSit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUp)
                    .addComponent(btnDel))
                .addGap(91, 91, 91))
        );

        setBounds(0, 0, 709, 541);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdSitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSitActionPerformed

    private void txtPesIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesIdKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPesIdKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        listarStiuacao();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Situacao obj = new Situacao();
        obj.setSituacao(txtSit.getText());
        try {
              SituacaoDAO dao = new SituacaoDAO();   
              dao.cadastrarSituacao(obj);
               
                listarStiuacao();
                limpaCampos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
           
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
         int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja atualizar a situação","Atenção",JOptionPane.YES_NO_OPTION);
        
         if(confirma == JOptionPane.YES_OPTION){
         Situacao obj = new Situacao();
         
         obj.setSituacao(txtSit.getText());
         obj.setIdsit(Integer.parseInt(txtIdSit.getText()));
         try {
              SituacaoDAO dao = new SituacaoDAO();   
              dao.editarSituacao(obj);
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
            listarStiuacao();
            limpaCampos();
         }
    }//GEN-LAST:event_btnUpActionPerformed

    private void tbSituacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSituacaoMouseClicked
        // TODO add your handling code here:
        setar_campo();
    }//GEN-LAST:event_tbSituacaoMouseClicked

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
         int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Excluir a situação","Atenção",JOptionPane.YES_NO_OPTION);
        
         if(confirma == JOptionPane.YES_OPTION){
         Situacao obj = new Situacao();
         
         obj.setIdsit(Integer.parseInt(txtIdSit.getText()));
         try {
              SituacaoDAO dao = new SituacaoDAO();   
              dao.deleteSituacao(obj);
              
              listarStiuacao();
              limpaCampos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
         }
    }//GEN-LAST:event_btnDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSituacao;
    private javax.swing.JTextField txtIdSit;
    private javax.swing.JTextField txtPesId;
    private javax.swing.JTextField txtPesSit;
    private javax.swing.JTextField txtSit;
    // End of variables declaration//GEN-END:variables
}
